# Generated on Fri Aug 09 09:51:04 EDT 2019
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app # for matching with kustomize
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app # for matching with kustomize
          image: docker.io/spring/testapp  # note, does not yet really exist
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080